### PR TITLE
HTTP send page improvement

### LINKED ISSUE #308: http, send page
Address input field is not wide enough to show the full address. 
Input should be verified as a valid address and have an error shown if it is not.
Amount input should not allow input over the valid amount size of this many digits 12345678.12345678 . Refer to the android app for rules on valid amount inputs.
The X to get ride of a row should not have a box around it or it looks too similar to the input boxes.  "Amount must be a non-zero positive number" shows for the amount, but it is located under the address box. Error should be under the proper input box. Also see proper error text from android. 'Add another address' should not be in a box that looks similar to the input fields. Reset button should instead be named Clear Fields. Rename Next button to Send. Send button should be grey until all needed fields are properly filled out. Send Max checkbox is failing, not sure why. The user should be able to collapse the list of custom inputs after they have selected the inputs they want to use.

Display additional fields that android shows,  Fee, Estimated Size, Balance After, Exchange Rate.

Support the Send to Account option as does android.

### PR DESCRIPTION
**Pull request by ademuanthony**
Resolves #308 
The following changes where made
- The address field was increased
- Instant address validation was implemented
- Errors in destination fields are shown immediately after the affected fields
image
- Added validation to the amount field to stop the user from specifying more than his balance for sending
image
- The send button will stay disabled until the send page is valid
image
image
- Implemented a function for getting the exchange rate from bitrex and show the rate to the user on the confirmation modal.
- Added two new functions to the `utils` package for estimating transaction fee and size and show this information on the transaction confirmation modal.
image
image
- Added 'send to account' feature with send max, add account, remove account and all the validations in 'send to address'
image
image
image
- Added field for entering dollar value as destination amount. The DCR field is automatically updated as the USD field is being changed and vice versa. Send max feature is available on the USD field.
image
- Input validation is available on the USD field
image
- Show USD value on the summary modal
image
-Modelled the buttons after the android app
image

image

### CODE REVIEW

File: nuklear/pagehandlers/transaction_details.go [hunk 1]
```diff
@@ -3,11 +3,11 @@ package pagehandlers
 import (
 	"strconv"
 
+	"fmt"
```
Comment (Sirmorrison) [inline nuklear/pagehandlers/transaction_details.go]: re-arrange import

File: web/routes/handlers.go [hunk 2]
```diff
@@ -11,7 +11,10 @@ import (
 	"github.com/raedahgroup/dcrlibwallet"
 	"github.com/raedahgroup/dcrlibwallet/txhelper"
 	"github.com/raedahgroup/godcr/app/config"
+	"github.com/raedahgroup/godcr/app/conversion/bitrex"
+	"github.com/raedahgroup/godcr/app/utils"
 	"github.com/raedahgroup/godcr/app/walletcore"
+	"github.com/raedahgroup/godcr/web/weblog"
 	"github.com/skip2/go-qrcode"
 	"math"
```
Comment (Sirmorrison) [inline web/routes/handlers.go]: re-arrange import

**Review by Sirmorrison — CHANGES_REQUESTED** [review]

**Review by Sirmorrison — APPROVED** [review]

File: app/conversion/bitrex/bitrex.go [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+		return 0, err
+	}
+	return summary.Rate * btcAmount, nil
+}
+
+func fetchMarketSummary(marketName string) (*marketSummary, error) {
+	url := fmt.Sprintf("https://api.bittrex.com/api/v1.1/public/getmarketsummary?market=%s", marketName)
+
+	httpClient := http.Client{
+		Timeout: time.Second * 2,
```
Comment (itswisdomagain) [inline app/conversion/bitrex/bitrex.go]: 2 seconds timeout seems small, no?

File: app/utils/utils.go [hunk 4]
```diff
@@ -32,3 +37,64 @@ func SplitAmountIntoParts(amount float64) []string {
...
+
+func EstimateSerializeSize(numberOfInputs int, destinations []txhelper.TransactionDestination) (int, error) {
+	outputs, err := makeTxOutputs(destinations)
+	if err != nil {
+		return 0, err
+	}
+
+	var changeAddresses []string
+	for _, destination := range destinations {
+		changeAddresses = append(changeAddresses, destination.Address)
```
Comment (itswisdomagain) [inline app/utils/utils.go:121]: `changeAddresses` and `outputs` are actually not the same.

I see that the new functions required are `EstimateFee` and `EstimateSerializeSize`.

These operations are already quite well handled in `dcrlibwallet`, so what I did was to export a public function that can be used from the `txhelper` package (`txhelper.EstimateTxFeeAndSize`). You'll need to update the dcrlibwallet version in go.mod and run `go mod tidy` to use these new functions.

Usage should be something like `txhelper.EstimateTxFeeAndSize(len(payload.utxos), payload.sendDestinations, payload.changeDestinations)`

File: web/routes/handlers.go [hunk 5]
```diff
@@ -113,11 +125,69 @@ func (routes *Routes) maxSendAmount(res http.ResponseWriter, req *http.Request)
...
+func (routes *Routes) getFeeAndSize(res http.ResponseWriter, req *http.Request) {
+	data := map[string]interface{}{}
+	defer renderJSON(data, res)
+
+	payload, err := retrieveSendPagePayload(req, routes.walletMiddleware.GenerateNewAddress)
+	if err != nil {
+		data["error"] = fmt.Sprintf("Cannot get summary: %s", err.Error())
+		return
+	}
+	// If no input is selected, use all inputs in the account to determine
```
Comment (itswisdomagain) [inline web/routes/handlers.go]: This comment needs to be updated. The reason we need all inputs is to properly determine the number of inputs to take into account when estimating fee and tx serialize size.

File: web/routes/handlers.go [hunk 6]
```diff
@@ -113,11 +125,69 @@ func (routes *Routes) maxSendAmount(res http.ResponseWriter, req *http.Request)
...
+
+func (routes *Routes) getFeeAndSize(res http.ResponseWriter, req *http.Request) {
+	data := map[string]interface{}{}
+	defer renderJSON(data, res)
+
+	payload, err := retrieveSendPagePayload(req, routes.walletMiddleware.GenerateNewAddress)
+	if err != nil {
+		data["error"] = fmt.Sprintf("Cannot get summary: %s", err.Error())
+		return
+	}
```
Comment (itswisdomagain) [inline web/routes/handlers.go:164]: Adding an empty line after each if block in this function would be helpful.

File: app/walletcore/helper.go [hunk 7]
```diff
@@ -81,12 +81,34 @@ func GetChangeDestinationsWithRandomAmounts(wallet Wallet, nChangeOutputs int, a
...
+func BuildTxDestinations(destinationAddresses, destinationAccounts,
+	destinationAmounts, sendMaxAmountValues []string, addressFunc func(accountNumber uint32) (string, error)) (
 	destinations []txhelper.TransactionDestination, totalAmount dcrutil.Amount, err error) {
 
-	for i := range destinationAddresses {
+	destinationAccountAddresses := make([]string, len(destinationAccounts))
+	for i, accountStr := range destinationAccounts {
+		account, err := strconv.ParseInt(accountStr, 10, 32)
+		if err != nil {
+			return nil, 0, err
```
Comment (itswisdomagain) [inline app/walletcore/helper.go]: `fmt.Errorf("Invalid account number")`

File: app/walletcore/helper.go [hunk 8]
```diff
@@ -81,12 +81,34 @@ func GetChangeDestinationsWithRandomAmounts(wallet Wallet, nChangeOutputs int, a
...
 }
 
-func BuildTxDestinations(destinationAddresses, destinationAmounts, sendMaxAmountValues []string) (
+func BuildTxDestinations(destinationAddresses, destinationAccounts,
+	destinationAmounts, sendMaxAmountValues []string, addressFunc func(accountNumber uint32) (string, error)) (
 	destinations []txhelper.TransactionDestination, totalAmount dcrutil.Amount, err error) {
 
-	for i := range destinationAddresses {
+	destinationAccountAddresses := make([]string, len(destinationAccounts))
+	for i, accountStr := range destinationAccounts {
```
Comment (itswisdomagain) [inline app/walletcore/helper.go]: `accountNumber` or `accountNumberStr`

File: app/walletcore/helper.go [hunk 9]
```diff
@@ -81,12 +81,34 @@ func GetChangeDestinationsWithRandomAmounts(wallet Wallet, nChangeOutputs int, a
 	return
 }
 
-func BuildTxDestinations(destinationAddresses, destinationAmounts, sendMaxAmountValues []string) (
+func BuildTxDestinations(destinationAddresses, destinationAccounts,
+	destinationAmounts, sendMaxAmountValues []string, addressFunc func(accountNumber uint32) (string, error)) (
```
Comment (itswisdomagain) [inline app/walletcore/helper.go]: `addressFunc` can be `generateAddress` or `generateAddressFn`

File: app/walletcore/helper.go [hunk 10]
```diff
@@ -81,12 +81,34 @@ func GetChangeDestinationsWithRandomAmounts(wallet Wallet, nChangeOutputs int, a
...
 	destinations []txhelper.TransactionDestination, totalAmount dcrutil.Amount, err error) {
 
-	for i := range destinationAddresses {
+	destinationAccountAddresses := make([]string, len(destinationAccounts))
```
Comment (itswisdomagain) [inline app/walletcore/helper.go:141]: Append to `destinationAddresses` instead of creating a new `destinationAccountAddresses` slice.

File: web/routes/helpers.go [hunk 11]
```diff
@@ -66,6 +66,7 @@ func retrieveSendPagePayload(req *http.Request) (payload *sendPagePayload, err e
 
 	// parse send destinations form data
 	destinationAddresses := req.Form["destination-address"]
+	destinationAccounts := req.Form["destination-account"]
```
Comment (itswisdomagain) [inline web/routes/helpers.go]: `destinationAccountNumbers`, `destination-account-number`

**Review by itswisdomagain — CHANGES_REQUESTED** [review]
Let's work on these changes first, will test and review more afterwards.

**Review by Sirmorrison — CHANGES_REQUESTED** [review]
image

image

*on the send page? `send to account` column doesn't show the input fields and when you return to `send to address` the input fields are also hidden until the page is refresh.

File: web/views/send.html [hunk 12]
```diff
@@ -82,50 +104,141 @@ <h5 class="card-title">Sending Decred</h5>
...
-                                                    class="btn btn-outline-secondary removeDestinationBtn"
-                                                    style="border: 1px solid #ced4da !important;" type="button">X</button>
                                         </div>
+                                    </template>
 
-                                        <div class="col-sm-12 invalid-feedback d-none"></div>
+                                    <div class="form-group mb-0">
+                                        <button type="button" data-action="click->send#newDestinationAccount"
+                                                class="btn btn-outline-primary shadow-sm">
+                                            Add another output
```
Comment (Sirmorrison) [inline web/views/send.html]: ` Add another output` should be ` Add another account`

**Review by Sirmorrison — CHANGES_REQUESTED** [review]

File: web/views/send.html (hunk 12 above)
Comment (ademuanthony) [reply web/views/send.html]: it was changed to output so that the user will not confuse it with creating a new account

File: app/utils/utils.go (hunk 4 above)
Comment (Sirmorrison) [reply app/utils/utils.go:121]: > 
> 
> `changeAddresses` and `outputs` are actually not the same.
> 
> I see that the new functions required are `EstimateFee` and `EstimateSerializeSize`.
> 
> These operations are already quite well handled in `dcrlibwallet`, so what I did was to export a public function that can be used from the `txhelper` package (`txhelper.EstimateTxFeeAndSize`). You'll need to update the dcrlibwallet version in go.mod and run `go mod tidy` to use these new functions.
> 
> Usage should be something like `txhelper.EstimateTxFeeAndSize(len(payload.utxos), payload.sendDestinations, payload.changeDestinations)`

have this request been implemented?

File: web/routes/handlers.go (hunk 5 above)
Comment (Sirmorrison) [reply web/routes/handlers.go]: > 
> 
> This comment needs to be updated. The reason we need all inputs is to properly determine the number of inputs to take into account when estimating fee and tx serialize size.

this also?

**Comment by Sirmorrison** [comment]
image
These issues should be looked at.

image
I think `add another output` should be `add another account`

**Comment by Sirmorrison** [comment]
image
I noticed that when i select `custom inputs` it brings out this `change output` at the bottom of the screen.
Now the issue is.. when i select an output say `1` then change my mind not to use `custom input` but `automatic input` instead, it clears everything but i still get this error at the bottom saying `Total change amount percentage must be equal to 100. Current total is 0` which prevents me from sending the fund.

**Comment by Sirmorrison** [comment]
I also noticed i can send funds to the address of same account... is that a normal something or an issue?

**Comment by ademuanthony** [comment]
> I also noticed i can send funds to the address of same account... is that a normal something or an issue?

yes

**Review by Sirmorrison — APPROVED** [review]

File: app/utils/utils.go (hunk 4 above)
Comment (ademuanthony) [reply app/utils/utils.go:121]: `changeAddresses` and `output` are used differently here though

File: app/rebase.txt [hunk 13]
```diff
@@ -0,0 +1 @@
+delete me again
```
Comment (itswisdomagain) [inline app/rebase.txt]: Please delete

File: app/utils/utils.go [hunk 14]
```diff
@@ -6,10 +6,12 @@ import (
 	"strconv"
 	"strings"
 
-	"github.com/decred/dcrd/dcrutil"
-
 	"github.com/raedahgroup/godcr/app/config"
 	"github.com/raedahgroup/godcr/app/walletcore"
+	"github.com/decred/dcrd/dcrutil"
```
Comment (itswisdomagain) [inline app/utils/utils.go:9]: Organize your imports alphabetically.

**Review by itswisdomagain — CHANGES_REQUESTED** [review]

File: web/routes/handlers.go [hunk 15]
```diff
@@ -81,14 +84,24 @@ func (routes *Routes) sendPage(res http.ResponseWriter, req *http.Request) {
...
 		"spendUnconfirmedFunds": routes.settings.SpendUnconfirmed,
 	}
+
+	if routes.settings.CurrencyConverter == "bitrex" {
+		exchangeRate, err := bitrex.DcrToUsd(1)
+		if err != nil {
+			weblog.LogError(fmt.Errorf("error fetching exchange rate: %s", err.Error()))
+		}
+
+		data["exchangeRate"] = fmt.Sprintf("%.8f", exchangeRate)
```
Comment (itswisdomagain) [inline web/routes/handlers.go]: This should be in an else block.

**Review by itswisdomagain — CHANGES_REQUESTED** [review]

**Review by itswisdomagain — APPROVED** [review]
