### PR TITLE
convert send amount from dcr unit to atom in walletrpcclient

### LINKED ISSUE #37: wrong amount unit for cli send command
`dcrcli send` asks for amount in DCR but amount debited is not in DCR. This issue has been fixed for the web server package in PR #30, specifically in [this comment](https://github.com/raedahgroup/dcrcli/pull/30/commits/174385aae1a6973615adbc7b8cca001c0e64ade4), just to replicate in the cli package

### PR DESCRIPTION
**Pull request by itswisdomagain**
Modified the `cli` and `web` packages to accept float64 amounts (fractional DCR amounts). While the core `walletrpcclient` package accepts this float64 amount value, it recognizes that what `dcrwallet` actually needs is the equivalent amount in Atoms (int64), so the `walletrpcclient` package converts the DCR amount to Atoms before passing to `dcrwallet` rpc.

Closes #37

### CODE REVIEW

**Comment by barisere** [comment]
I have verified that this PR fixes issue #37.

**Review by barisere — APPROVED** [review]

File: walletrpcclient/walletrpcclient.go [hunk 1]
```diff
@@ -59,7 +59,15 @@ func (c *Client) connect(address, cert string, noTLS bool) (*grpc.ClientConn, er
 	return conn, nil
 }
 
-func (c *Client) Send(amount int64, sourceAccount uint32, destinationAddress, passphrase string) (*SendResult, error) {
+func (c *Client) Send(amountInDCR float64, sourceAccount uint32, destinationAddress, passphrase string) (*SendResult, error) {
+	// convert amount from float64 DCR to int64 Atom as required by dcrwallet ConstructTransaction implementation
+	amountInAtom, err := dcrutil.NewAmount(amountInDCR)
```
Comment (barisere) [inline walletrpcclient/walletrpcclient.go:64]: @itswisdomagain 
Keeping the conversion to `Amount` type in the `walletrpcclient` package is a clean approach. I like it. :+1:

**Review by barisere — APPROVED** [review]
