### PR TITLE
Fixed the bug seen when wallet does not exist and user chose not to create it

### LINKED ISSUE #179: error/crash when running godcr if wallet doesn't exist
### Cli
Running a godcr command e.g. `godcr stakeinfo` without having a wallet, prompts user to create a wallet. If user choses not to create a wallet at the moment, godcr crashes.
screenshot 2019-01-25 at 2 04 57 pm

### Nuklear
The UI launch is canceled and the following error is printed after the app quits.`fatal error: unexpected signal during runtime execution`

### qt
UI launch is canceled without any message.

### terminal
If wallet doesn't exist, user is prompted to create wallet. If user does not accept to create wallet, the terminal UI is displayed even though the features in it cannot be used without a wallet. When the app is quit, the following message is displayed:
```
Blockchain sync failed to start. wallet_not_loaded
wallet_not_loaded
```

If user accepts to create a wallet, wallet is created. After wallet creation, user is asked if to sync blockchain. **Error is** blockchain sync happens whether user agrees to sync or not.

### PR DESCRIPTION
**Pull request by ademuanthony**
Resolves #179

### CODE REVIEW

File: cli/runner/helpers.go [hunk 1]
```diff
@@ -24,19 +24,19 @@ func CommandRequiresWallet(command flags.Commander) bool {
 
 // prepareWallet gets a wallet ready for use by opening the wallet using the provided walletMiddleware
 // and performing sync operations if requested
-func prepareWallet(ctx context.Context, middleware app.WalletMiddleware, options config.CliOptions) error {
+func prepareWallet(ctx context.Context, middleware app.WalletMiddleware, options config.CliOptions) (bool, error) {
```
Comment (itswisdomagain) [inline cli/runner/helpers.go]: Using named return variables will make this function easier to understand. `(walletExists bool, err 
 error)`. You can then simply `return` in lines 30, 36 and 39

**Review by itswisdomagain — CHANGES_REQUESTED** [review]

**Review by itswisdomagain — APPROVED** [review]
