### PR TITLE
History pagination

### LINKED ISSUE #210: http history page - broken pipe error
The http server sometimes crashes after visiting or attempting to visit the history page. The terminal shows the following message:
screenshot 2019-02-28 at 1 07 29 pm

### PR DESCRIPTION
**Pull request by itswisdomagain**
History txs are now loaded in batches with infinite scroll in http and terminal (scrolling to the bottom loads next batch) while nuklear and cli uses pagination.

This PR also adds ability to view tx details while displaying history on cli. Also fixes #210 

**Changes that may not be visible in following screenshots**:
- The addition of "UTC" to the tx dates on all interfaces; so dates display as `2019-03-29 07:24:34 UTC`
- "#" instead of "S/N" for first column header on all interfaces

### http (infinite scroll with js enabled)
Screenshot 2019-03-31 at 9 50 19 AM

### http (pagination when js is disabled)
Screenshot 2019-03-31 at 9 46 13 AM

### http (sticky column headers on scroll)
Screenshot 2019-04-01 at 4 49 42 AM

### cli
Screenshot 2019-03-31 at 9 42 31 AM

### cli (view tx details)
Screenshot 2019-04-01 at 6 28 46 AM

### nuklear
Screenshot 2019-03-31 at 9 53 12 AM

### terminal
Screenshot 2019-03-31 at 9 48 24 AM

### CODE REVIEW

File: nuklear/handlers/history.go [hunk 1]
```diff
@@ -0,0 +1,112 @@
+package handlers
+
+import (
+	"context"
+	"fmt"
+	"github.com/aarzilli/nucular"
```
Comment (ademuanthony) [inline nuklear/handlers/history.go:7]: rearrange and sort

File: web/static/app/src/controllers/history_controller.js [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+      if (direction >= 0 && direction < directions.length) {
+        return directions[direction]
+      }
+      return 'Unclear'
+    }
+
+    let n = this.historyTableTarget.querySelectorAll('tr').length
+
+    const txRows = txs.map(tx => {
+      return `<tr>
```
Comment (ademuanthony) [inline web/static/app/src/controllers/history_controller.js]: can we have this as a template in the view instead?

**Review by ademuanthony — CHANGES_REQUESTED** [review]
Just a few changes

**Review by ademuanthony — APPROVED** [review]
ready
